/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.quickfds.api.kotlin-spring-library-conventions")
}

dependencies {
    implementation(project(":lib"))
    implementation(libs.commons.text)
}
