/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.quickfds.api.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":lib"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.quickfds.api.app.AppKt")
}
